<?php echo $this->flashSession->output();?> 

<br></br>
<br></br>

<div class="row">
    <div class="col-sm">
     
    </div>
    <div class="col-sm">

<form action="" method="post" enctype="multipart/form-data">
<center>
    <label>ชื่อกิจกรรม</label>
    <input type="text" class="form-control" placeholder="ชื่อกิจกรรม" required name="name">
    <br><label>วันที่</label>
    <input type="date" class="form-control" placeholder="mm/dd/yyyy" min="2018-01-01" max="2019-12-31" required name="date">
    <br><label>รายละเอียด</label>
    <textarea class="form-control" placeholder="รายละเอียด" required rows="4" name="details"></textarea>
    <br><label>ภาพกิจกรรม</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
    <hr><button type="submit" class="btn btn-info">submit</button>
    <a href="<?php echo $this->url->getBaseUri(). 'event/'; ?>" class="btn btn-warning">Back</a>
</center>
</form>

    </div>
<div class="col-sm">
    </div>
</div>