<br></br>
<br></br>

<center><h1>ACTIVITIES.</h1></center>
<a href="<?php echo $this->url->getBaseUri().'event/add' ?>" class="btn btn-info"> Add </a>
<table data-toggle="table" class="table">
    <thead>
        <tr>
            <th data-field="id"> No. </th>
            <th data-field="name"> Activity </th>
            <th data-field="date"> Date </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php
    $id=$this->session->get('memberAuthen');
    $act = Event::find("");
    for ($i=0;$i<count($act);$i++){?>
      <tr>
        <th scope="row"><?php echo "$i"+1 ?></th>
        <td><?php
          echo $act[$i]->name; ?></td>
        <td><?php echo $act[$i]->date; ?></td>
        <td><a style="color:white;" href="<?php echo $this->url->getBaseUri(); ?>event/edit/<?php echo $act[$i]->id;?>" class="btn btn-info" id="edit<?php echo $act[$i]->id;?>" name="edit<?php echo $act[$i]->id;?>" value="<?php echo $act[$i]->id;?>">edit</a></td>
        <td><a href="<?php echo $this->url->getBaseUri(); ?>event/del/<?php echo $act[$i]->id;?>" class="btn btn-danger">delete</a></td>
      </tr>
    <?php }?>          
    </tbody>
</table>      

<center><a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a></center>


<!-- ตัวเก่า ลำดับไม่เรียง -->
<!-- <?php foreach($data as $item){?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->name ?></td>
                <td><?php echo $item->date ?></td>
                <td><a href="<?php echo $this->url->getBaseUri().'event/edit/'.$item->id; ?>" class="btn btn-warning">edit</a></td>
                <td><a href="<?php echo $this->url->getBaseUri().'event/del/'.$item->id; ?>" class="btn btn-danger navbar-btn">delete</a></td>
            </tr>
        <?php } ?> -->