<section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h1 class="section-heading text-white">About Me!</h1><br></br>
            <img class="img-fluid mb-5 d-block mx-auto" src="<?php echo $this->url->getBaseUri(); ?>public/img/bbun.png" alt="">
            <hr class="light my-4">
            <h1><p class="text-faded mb-4">นายปฐมภพ สุนันตา <br>590610639</br></p></h1>
            <!-- <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a> -->
          </div>
        </div>
      </div>
      <center><a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a></center>
    </section>