<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phalcon PHP Framework</title>
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 
  </head>
    <body id="page-top" >

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Bbun Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>event">Event</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>about">About</a>
            </li>
            <!-- <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contact</a>
            </li> -->
          </ul>
           <ul class="navbar-nav  navbar-right">     
   	<?php if($this->session->has('memberAuthen')) {?> 
     
   
      <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>profile"><?php echo $this->session->get('memberEmail');?></a>
     </li>
     <li class="nav-item mx-0 mx-lg-1">
     		<a  class="btn btn-danger navbar-btn" href="authen/signOut"> Logout </a> 
     </li>  
    <?php } else {?>
      <li class="nav-item mx-0 mx-lg-1">
       <a href="authen" class="btn btn-outline-primary"> Login </a>
      </li>    
     <li class="nav-item mx-0 mx-lg-1">
       <a href="authen/signUp" class="btn btn-outline-info"> Sign Up </a>
      </li>
      <?php }?>
    </ul>
        </div>
      </div>
    </nav>

    <!-- Header Bar-->
   
    <header class="masthead bg-primary text-white">
       <div class="container"><?php echo $this->getContent(); ?></div>      
    </header>

   
    <!-- Footer -->  

    <div class="copyright py-4 text-center text-black">
      <div class="container">
        <small>Copyright &copy; bbun Website 2018</small>
      </div>
    </div>

    <!-- Activities -->
    <!-- <div class="row">
    <div class="col-sm">
    </div>
    <div class="table-responsive"> 
    <h1><center>ACTIVITIES.</center></h1>
    
    <center><br><a href="<?php echo $this->url->getBaseUri(); ?>add" class="btn btn-success">ADD</a></br></center>
    <br><center><table class="table table-striped table-light" style="color:gray;">
            
              <thead>
                <tr style="color:black;">
                  <th scope="col">No.</th>
                  <th scope="col">Activity</th>
                  <th scope="col">Date</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              <?php
              $id=$this->session->get('memberAuthen');
              $act = Event::find("");
              for ($i=0;$i<count($act);$i++){?>
                <tr>
                  <th scope="row"><?php echo "$i"+1 ?></th>
                  <td><?php
                    echo $act[$i]->name; ?></td>
                  <td><?php echo $act[$i]->date; ?></td>
                  <td><a style="color:white;" href="<?php echo $this->url->getBaseUri(); ?>event/setId/<?php echo $act[$i]->id;?>" class="btn btn-info" id="edit<?php echo $act[$i]->id;?>" name="edit<?php echo $act[$i]->id;?>" value="<?php echo $act[$i]->id;?>">edit</a></td>
                  <td><a href="<?php echo $this->url->getBaseUri(); ?>event/deleteId/<?php echo $act[$i]->id;?>" class="btn btn-danger">delete</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table><center></br>
          </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
  <center><a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a></center> -->
  


    <!-- About  -->
    <!-- <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">About Me!</h2><br></br>
            <img class="img-fluid mb-5 d-block mx-auto" src="<?php echo $this->url->getBaseUri(); ?>public/img/bbun.png" alt="">
            <hr class="light my-4">
            <p class="text-faded mb-4">นายปฐมภพ สุนันตา <br>590610639</br></p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
          </div>
        </div>
      </div>
    </section> -->


  </body>
  
</html>
